name: beacon_kontakt
description: Wrapper Plugin for Official Kontakt.io Android and iOS SDK(s), Plugin works to communicate with Bluetooth Low Energy devices with additional benefits on Kontakt devices
version: 0.1.0
homepage:

environment:
  sdk: '>=2.19.4 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.0.2
  simple_ripple_animation: ^0.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: devberkay.kontakt.beacon_kontakt
        pluginClass: BeaconKontaktPlugin
      ios:
        pluginClass: BeaconKontaktPlugin
