import 'dart:convert';
// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'ibeacon_device.freezed.dart';
// optional: Since our IBeaconDevice class is serializable, we must add this line.
// But if IBeaconDevice was not serializable, we could skip it.
part 'ibeacon_device.g.dart';

@freezed
class IBeaconDevice with _$IBeaconDevice {
  const factory IBeaconDevice(
      {
      required String proximityUUID,
      required String major,
      required int minor,
      required int proximity,
      String? userId, // this is later to be fetched from firestore
      int? updatedAt, // msSinceEpoch
      String? rssi,
      String? txPower // only android
      }) = _IBeaconDevice;

  factory IBeaconDevice.fromJson(Map<String, Object?> json) =>
      _$IBeaconDeviceFromJson(json);
}
