import 'dart:convert';
// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'ibeacon_device.freezed.dart';
// optional: Since our IBeaconDevice class is serializable, we must add this line.
// But if IBeaconDevice was not serializable, we could skip it.
part 'ibeacon_device.g.dart';

@freezed
class IBeaconDevice with _$IBeaconDevice {
  const factory IBeaconDevice(
      {
      String? proximityUUID,
      int? major,
      int? minor,
      String? userId,
      String? uniqueId,
      String? mac,
      int? proximity,
      int? timestamp, // msSinceEpoch
      int? rssi,
      int? txPower // only android
      }) = _IBeaconDevice;

  factory IBeaconDevice.fromJson(Map<String, Object?> json) =>
      _$IBeaconDeviceFromJson(json);
}
