import 'dart:convert';
// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'ibeacon_device.freezed.dart';
// optional: Since our ISecureProfile class is serializable, we must add this line.
// But if ISecureProfile was not serializable, we could skip it.
part 'ibeacon_device.g.dart';


@freezed
class ISecureProfile with _$ISecureProfile {
  const factory ISecureProfile({
    required String proximityUUID,
    required String major,
    required int minor,
    String? rssi,
    String? txPower
  }) = _ISecureProfile;

  factory ISecureProfile.fromJson(Map<String, Object?> json)
      => _$ISecureProfileFromJson(json);
}